version: '3.8'

services:
  # Frontend - Streamlit
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - kognia-network
    restart: unless-stopped

  # API - FastAPI
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./backend:/app/backend
      - ./llms:/app/llms
      - ./agents:/app/agents
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=kognia_one_db
      - REDIS_HOST=redis
      - API_PORT=8000
      - APP_SECRET_KEY=your_app_secret_key
      - DOCKER_ENV=true
    depends_on:
      - db
      - redis
    networks:
      - kognia-network
    restart: unless-stopped

  # Banco de dados MySQL
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=kognia_one_db
    networks:
      - kognia-network
    restart: unless-stopped

  # Redis para cache e filas
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - kognia-network
    restart: unless-stopped

networks:
  kognia-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: