services:
  db:
    image: mysql:5.7.44
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=kognia_one_db
    volumes:
       - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: