version: "3.8"

services:
  # Frontend - Flask
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=${API_URL:-http://api:8000}
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    depends_on:
      - api
    networks:
      - kealabs-network
    restart: unless-stopped

  # API - FastAPI
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./backend:/app/backend
      - ./llms:/app/llms
      - ./agents:/app/agents
    environment:
      - DB_HOST=${DB_HOST:-mysql_eden_jardins_eden_mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-eden}
      - DB_PASSWORD=${DB_PASSWORD:-eden2025@!}
      - DB_NAME=${DB_NAME:-eden_db}
      - API_PORT=${API_PORT:-8000}
      - APP_SECRET_KEY=${APP_SECRET_KEY:-your_app_secret_key}
      - DOCKER_ENV=${DOCKER_ENV:-true}
    # depends_on removido - usando banco externo
    networks:
      - kealabs-network
    restart: unless-stopped

  # Banco de dados MySQL (Externo - não precisa do container)
  # Usando banco externo: mysql://eden:eden2025@!@72.60.140.128:2621/eden_db





networks:
  kealabs-network:
    driver: bridge

# volumes removidos - usando banco externo
# volumes:
#   db_data:

