version: '3.8'

services:
  # Frontend - Flask
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://api:8000
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - api
    networks:
      - kognia-network
    restart: unless-stopped

  # API - FastAPI
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./backend:/app/backend
      - ./llms:/app/llms
      - ./agents:/app/agents
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=kognia_one_db
      - API_PORT=8000
      - APP_SECRET_KEY=your_app_secret_key
      - DOCKER_ENV=true
      - N8N_URL=http://n8n:5678
      - N8N_API_KEY=
    depends_on:
      - db
      - n8n
    networks:
      - kognia-network
    restart: unless-stopped

  # Banco de dados MySQL
  db:
    image: mysql:5.7.44
    ports:
      - "3306:3306"
    volumes:
       - db_data:/var/lib/mysql
       - ./init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
       - ./init-n8n-db.sql:/docker-entrypoint-initdb.d/02-init-n8n-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=kognia_one_db
      - MYSQL_INITDB_SKIP_TZINFO=1
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    networks:
      - kognia-network
    restart: unless-stopped

  # n8n - Workflow Automation
  n8n:
    image: n8nio/n8n:1.17.1
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=db
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=n8n_db
      - DB_MYSQLDB_USER=root
      - DB_MYSQLDB_PASSWORD=root_password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n-data:/home/node/.n8n
    depends_on:
      - db
    networks:
      - kognia-network
    restart: unless-stopped

networks:
  kognia-network:
    driver: bridge

volumes:
  db_data:
  n8n-data: