version: '3.8'

services:
  # Frontend - Streamlit
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - kognia-network
    restart: unless-stopped

  # API - FastAPI
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./backend:/app/backend
      - ./llms:/app/llms
      - ./agents:/app/agents
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=kognia_one_db
      - REDIS_HOST=redis
      - API_PORT=8000
      - APP_SECRET_KEY=your_app_secret_key
      - DOCKER_ENV=true
      - N8N_URL=http://n8n:5678
    depends_on:
      - db
      - redis
    networks:
      - kognia-network
    restart: unless-stopped

  # n8n - Workflow Automation
  n8n:
    image: n8nio/n8n:0.234.0
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_HOST=n8n
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=db
      - DB_MYSQLDB_PORT=3306
      - DB_MYSQLDB_DATABASE=n8n_db
      - DB_MYSQLDB_USER=root
      - DB_MYSQLDB_PASSWORD=root_password
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_ENCRYPTION_KEY=your_encryption_key_here
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - GENERIC_TIMEZONE=UTC
    depends_on:
      - db
    networks:
      - kognia-network
    restart: unless-stopped

  # Banco de dados MySQL
  db:
    image: mysql:5.7.44
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=kognia_one_db
      - MYSQL_INITDB_SKIP_TZINFO=1
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    networks:
      - kognia-network
    restart: unless-stopped

  # Redis para cache e filas
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - kognia-network
    restart: unless-stopped

networks:
  kognia-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  n8n-data: